Repository WebAppTeamPJ/HanulDure, pull requests merged in 2024-05, with the labels that each got.

#11 #8 [feature/board] -> [main]
  haunlduredb.txt
  src/main/java/com/hanuldure/project/config/ContextConfiguration.java
  src/main/java/com/hanuldure/project/controller/CommunityBoardController.java
  src/main/java/com/hanuldure/project/dao/CommunityDAO.java
  src/main/java/com/hanuldure/project/dao/impl/CommunityDAOImpl.java
  src/main/java/com/hanuldure/project/dto/CommunityTO.java
  src/main/java/com/hanuldure/project/mapper/CommunityMapper.java
  src/main/java/com/hanuldure/project/service/CommunityService.java
  src/main/resources/static/css/communitydetail.css
  src/main/resources/static/css/communitywrite.css
  src/main/resources/static/image/img.png
  src/main/resources/static/js/communitydetailbtonoff.js
  src/main/resources/static/js/communitywritebtclick.js
  src/main/resources/templates/community/communitydetail.html
  src/main/resources/templates/community/communityedit.html
  src/main/resources/templates/community/communitywrite.html
Labels: ✨PR

#10 Hanul dure/login
  build.gradle
  src/main/java/com/hanuldure/project/controller/FirstPageAndLoginPageController.java
  src/main/java/com/hanuldure/project/controller/MainController.java
  src/main/java/com/hanuldure/project/model/dto/MemberDTO.java
  src/main/java/com/hanuldure/project/model/dto/firstpageDTO.java
  src/main/resources/static/css/firstpage.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/logincreatemember.css
  src/main/resources/static/css/loginsearchid.css
  src/main/resources/static/css/loginserchpwd.css
  src/main/resources/static/image/eximage.png
  src/main/resources/static/image/loginbackground.png
  src/main/resources/static/image/logo.png
  src/main/resources/static/image/mainbackground.png
  src/main/resources/templates/login/createmember.html
  src/main/resources/templates/login/firstpage.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/login/searchid.html
  src/main/resources/templates/login/searchpwd.html
  src/main/resources/templates/main/main.html
Labels: ✨PR

#14 [Feature/expToCommunity] (#4, #5, #6) 커뮤메인, 글목록, 체험주최, 체험상세 통합
  src/main/java/com/hanuldure/project/controller/CommunityController.java
  src/main/java/com/hanuldure/project/controller/ExpController.java
  src/main/java/com/hanuldure/project/model/dto/ExpDTO.java
  src/main/resources/static/css/expDetail.css
  src/main/resources/static/css/expHostSub.css
  src/main/resources/static/party/community_main.css
  src/main/resources/static/party/community_partyApply.css
  src/main/resources/static/party/logo.svg
  src/main/resources/static/party/party_list_background.svg
  src/main/resources/static/party/search.png
  src/main/resources/static/party/test.png
  src/main/resources/templates/community/boardList.html
  src/main/resources/templates/community/main.html
  src/main/resources/templates/community/partyApply.html
  src/main/resources/templates/community/partyList.html
  src/main/resources/templates/main/expDetail.html
  src/main/resources/templates/main/expHostSub.html
Labels: ✨PR

#15 [feature/profile] -> [main]
  build.gradle
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/java/com/hanuldure/project/controller/UserProfileController.java
  src/main/java/com/hanuldure/project/model/Exp.java
  src/main/java/com/hanuldure/project/model/Farmer.java
  src/main/java/com/hanuldure/project/model/User.java
  src/main/java/com/hanuldure/project/service/ExpService.java
  src/main/java/com/hanuldure/project/service/FarmerService.java
  src/main/java/com/hanuldure/project/service/UserService.java
  src/main/resources/static/css/farmerprofile.css
  src/main/resources/static/css/userprofile.css
  src/main/resources/static/img/exp.png
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/user_image.png
  src/main/resources/templates/profile/farmerprofile.html
  src/main/resources/templates/profile/userprofile.html
Labels: ✨PR

#16 #16 [Feature/board2] -> [main]
  src/main/java/com/hanuldure/project/controller/CommunityBoardController.java
  src/main/java/com/hanuldure/project/dao/CommunityDAO.java
  src/main/java/com/hanuldure/project/dao/impl/CommunityDAOImpl.java
  src/main/java/com/hanuldure/project/mapper/CommunityMapper.java
  src/main/java/com/hanuldure/project/service/CommunityService.java
  src/main/resources/static/js/communitydetailbtonoff.js
  src/main/resources/templates/community/communitydetail.html
  src/main/resources/templates/community/communityedit.html
Labels: ✨PR

#20 [hotfix/linkPages] (#19, #21) 버튼 페이지 간 이동 누락, 농업인 프로필 출력 누락 수정
  src/main/java/com/hanuldure/project/controller/CommunityController.java
  src/main/java/com/hanuldure/project/controller/ExpController.java
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/resources/templates/community/boardList.html
  src/main/resources/templates/community/main.html
  src/main/resources/templates/community/partyList.html
  src/main/resources/templates/login/firstpage.html
  src/main/resources/templates/main/expDetail.html
Labels: 🚨bug, ✨PR

#23 [hoxfix/boardPage] (#22) 모집글/자유글 비 선택시 form 전달을 막고 알람을 띄워줌
  src/main/resources/static/js/communitywritebtclick.js
  src/main/resources/templates/community/communitywrite.html
Labels: 🚨bug, ✨PR, 🔥hoxfix

#24 #18 삭제된 페이지 검색 시 나오는 페이지 추가
  src/main/java/com/hanuldure/project/controller/CommunityBoardController.java
  src/main/resources/static/css/errorpage.css
  src/main/resources/static/image/errorimg.png
  src/main/resources/templates/error/errorpage.html
Labels: ✨PR

#27 #26 회원가입 후 데이터베이스에 회원 등록 기능, 로그인 기능
  src/main/java/com/hanuldure/project/controller/FirstPageAndLoginPageController.java
  src/main/java/com/hanuldure/project/dao/MemberDAO.java
  src/main/java/com/hanuldure/project/mapper/MemberMapper.java
  src/main/java/com/hanuldure/project/model/dto/MemberDTO.java
  src/main/java/com/hanuldure/project/service/MemberService.java
  src/main/resources/templates/login/createmember.html
  src/main/resources/templates/login/login.html
Labels: ✨PR

#30 #30 [feature/board2] -> main
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/java/com/hanuldure/project/dao/ProfileDAO.java
  src/main/java/com/hanuldure/project/dto/MemberDTO.java
  src/main/java/com/hanuldure/project/mapper/ProfileMapper.java
  src/main/java/com/hanuldure/project/service/ProfileService.java
  src/main/resources/templates/profile/farmerprofile.html
  src/main/resources/templates/profile/userprofile.html
Labels: ✨PR

#31 #31 (#29, #28)밑에 test명시문 삭제, 이동 주소값 올바르게 설정
  src/main/java/com/hanuldure/project/controller/CommunityBoardController.java
  src/main/java/com/hanuldure/project/dto/CommunityTO.java
  src/main/java/com/hanuldure/project/mapper/CommunityMapper.java
  src/main/java/com/hanuldure/project/service/CommunityService.java
  src/main/resources/static/css/expDetail.css
  src/main/resources/static/img/exp.png
  src/main/resources/templates/community/communitydetail.html
  src/main/resources/templates/community/communityedit.html
  src/main/resources/templates/community/communitywrite.html
  src/main/resources/templates/main/expDetail.html
Labels: ✨PR

#34 [Feature/board3] -> [main]
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/java/com/hanuldure/project/controller/UserProfileController.java
  src/main/java/com/hanuldure/project/dao/ProfileDAO.java
  src/main/java/com/hanuldure/project/dto/ExpApplyDTO.java
  src/main/java/com/hanuldure/project/mapper/ProfileMapper.java
  src/main/java/com/hanuldure/project/model/dto/ExpDTO.java
  src/main/java/com/hanuldure/project/service/ProfileService.java
  src/main/resources/static/css/farmerprofile.css
  src/main/resources/static/img/exp1.png
  src/main/resources/templates/profile/farmerprofile.html
  src/main/resources/templates/profile/userprofile.html
Labels: ✨PR

#35 Feature/login2 세션 기능 추가, 비밀번호찾기, 아이디 찾기 기능 추가
  src/main/java/com/hanuldure/project/controller/FirstPageAndLoginPageController.java
  src/main/java/com/hanuldure/project/dao/FirstPageDAO.java
  src/main/java/com/hanuldure/project/dao/MemberDAO.java
  src/main/java/com/hanuldure/project/mapper/FirstPageMapper.java
  src/main/java/com/hanuldure/project/mapper/MemberMapper.java
  src/main/java/com/hanuldure/project/model/dto/FirstPageDTO.java
  src/main/java/com/hanuldure/project/model/dto/firstpageDTO.java
  src/main/java/com/hanuldure/project/model/session/SessionKey.java
  src/main/java/com/hanuldure/project/service/FirstPageService.java
  src/main/java/com/hanuldure/project/service/MemberService.java
  src/main/resources/templates/login/createmember.html
  src/main/resources/templates/login/firstpage.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/login/searchid.html
  src/main/resources/templates/login/searchpwd.html
Labels: ✨PR

#36 [develop/communityDB] (#33) 체험 주최 신청 기능 보완 및 DB 삽입
  src/main/java/com/hanuldure/project/controller/ExpController.java
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/java/com/hanuldure/project/controller/UserProfileController.java
  src/main/java/com/hanuldure/project/mapper/ExpMapper.java
  src/main/java/com/hanuldure/project/model/dto/ExpDTO.java
  src/main/java/com/hanuldure/project/model/dto/ExpReviewDTO.java
  src/main/java/com/hanuldure/project/service/ExpService.java
  src/main/resources/com/hanuldure/project/mapper/ExpMapper.xml
  src/main/resources/static/party/community_main.css
  src/main/resources/templates/community/communityedit.html
  src/main/resources/templates/community/communitywrite.html
  src/main/resources/templates/community/main.html
  src/main/resources/templates/community/partyList.html
  src/main/resources/templates/login/firstpage.html
  src/main/resources/templates/main/expDetail.html
  src/main/resources/templates/main/expHostSub.html
  src/main/resources/templates/main/expRequest.html
Labels: ✨PR

#42 main<-Feature/login3
  src/main/java/com/hanuldure/project/controller/FirstPageAndLoginPageController.java
  src/main/java/com/hanuldure/project/dao/ProfileDAO.java
  src/main/java/com/hanuldure/project/mapper/ProfileMapper.java
  src/main/java/com/hanuldure/project/service/ProfileService.java
  src/main/resources/static/css/firstpage.css
  src/main/resources/static/img/exp2.png
  src/main/resources/static/img/exp3.png
  src/main/resources/templates/login/firstpage.html
Labels: ✨PR

#44 [develop/communityDB] (#40) 게시글 목록 타임리프 이용 출력
  haunlduredb.txt
  src/main/java/com/hanuldure/project/controller/CommunityController.java
  src/main/java/com/hanuldure/project/controller/FarmerProfileController.java
  src/main/java/com/hanuldure/project/controller/FirstPageAndLoginPageController.java
  src/main/java/com/hanuldure/project/controller/UserProfileController.java
  src/main/java/com/hanuldure/project/dao/CommunityDAO.java
  src/main/java/com/hanuldure/project/mapper/CommunityMapper.java
  src/main/java/com/hanuldure/project/service/CommunityService.java
  src/main/resources/static/css/expDetail.css
  src/main/resources/static/css/header.css
  src/main/resources/static/party/community_main.css
  src/main/resources/static/party/community_partyApply.css
  src/main/resources/templates/common/header.html
  src/main/resources/templates/community/boardList.html
  src/main/resources/templates/community/main.html
  src/main/resources/templates/community/partyApply.html
  src/main/resources/templates/community/partyList.html
  src/main/resources/templates/login/firstpage.html
  src/main/resources/templates/profile/farmerprofile.html
  src/main/resources/templates/profile/userprofile.html
Labels: ⚡Feature, ✨PR
